apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  # the name of the PVC, which will be referenced by pods or other resources
  name: postgres-pvc

spec:
  # defines the access mode for the volume
  accessModes:
    # the volume can be mounted as read-write by a single node
    - ReadWriteOnce

  resources:
    # specifies the storage resources requested
    requests:
      # the amount of storage requested for the volume
      storage: 1Gi

  # specifies the storage class to use
  storageClassName: standard
