name: Auto failure workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: exit 1 # Simulating failure for testing

      - name: Tag successful commit
        if: ${{ success() }}
        run: |
          TAG_NAME="successful-$(date +'%Y%m%d%H%M%S')"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME

  revert-main:
    # Depend on build-and-test and always run if it fails
    needs: build-and-test
    if: ${{ failure() }} # Run this job if any previous job failed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch tags
        run: git fetch --tags
        
      - name: Find the last successful tag
        id: find_tag
        run: |
          LAST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "last_successful_tag=$LAST_TAG" >> $GITHUB_ENV
          echo "::set-output name=last_tag::$LAST_TAG"
        
      - name: Reset all except workflow files
        run: |
          if [ -z "${{ steps.find_tag.outputs.last_tag }}" ]; then
          echo "No successful tag found. Exiting."
          exit 1           
          fi
        
          git stash push -m "Stash workflow files" .github/workflows/*
          git reset --hard ${{ steps.find_tag.outputs.last_tag }}
          git stash apply --index
          git add .
          git reset .github/workflows/*
          git commit -m "Reverted to ${{ steps.find_tag.outputs.last_tag }} excluding workflow files"
          git push origin main --force
        