name: Auto failure workflow

on:
  push:
    branches:
      - gitactions

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: exit 0 # Simulate a failure for demonstration purposes

      - name: Tag successful commit
        if: ${{ success() }} # Ensure this only runs if previous steps succeed
        run: |
          TAG_NAME="successful-$(date +'%Y%m%d%H%M%S')"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME
