name: Validate and Initialize Infrastructure

on:
  push:
    branches:
      - gitactions
  workflow_dispatch:

jobs:
  validate-and-initialize-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: "latest"
          project_id: "idata2502-ci-cd"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure/terraform/prod/

      - name: Terraform Refresh
        run: terraform refresh
        working-directory: infrastructure/terraform/prod

      - name: Terraform Plan
        run: terraform plan
        working-directory: infrastructure/terraform/prod

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: infrastructure/terraform/prod/tfplan

      - name: Terraform Apply with Approval
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply tfplan
        working-directory: infrastructure/terraform/prod
